# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShuffleFiles < Formula
  desc "This is a CLI tool which shuffles the files in the directory"
  homepage "https://dotoca.net/shuffle-files/"
  version "0.2.0"

  on_macos do
    url "https://github.com/xvoland/shuffle-files/releases/download/v0.2.0/shuffle-files_0.2.0_darwin_all.tar.gz"
    sha256 "d070673ca874f4d8192474182812cbb4a37e8dd3036b398967cde6580f9482d0"

    def install
      bin.install "shuffle-files"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/xvoland/shuffle-files/releases/download/v0.2.0/shuffle-files_0.2.0_linux_amd64.tar.gz"
      sha256 "4655d8e1820925278ae0962d4074ab06bfdb02fbbcbbf8c982d8041f849dcf53"

      def install
        bin.install "shuffle-files"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xvoland/shuffle-files/releases/download/v0.2.0/shuffle-files_0.2.0_linux_arm64.tar.gz"
      sha256 "c329ae3542d830a35d99eb62283be5301417baa906da97614a4761aedb28307b"

      def install
        bin.install "shuffle-files"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/xvoland/shuffle-files/releases/download/v0.2.0/shuffle-files_0.2.0_linux_armv6.tar.gz"
      sha256 "4c6cc1218375bbdff329ebf8cd7d5a0035cf3833d9a704036ac6d23687f8c98b"

      def install
        bin.install "shuffle-files"
      end
    end
  end
end
